"""
MTConnect SAMPLE Category Types

All SAMPLE type DataItems from MTConnect v2.6 normative model (SampleEnum).
Samples report continuously variable or analog numeric data values.

Reference: MTConnect Standard v2.6 Normative Model - SampleEnum
"""

from enum import Enum, auto


class SampleType(Enum):
    """All SAMPLE types from MTConnect v2.6 normative model"""
    ACCELERATION = auto()  # Positive rate of change of velocity
    ACCUMULATED_TIME = auto()  # Accumulated time for an activity or event
    AMPERAGE_AC = auto()  # Electrical current that reverses direction at regular short intervals
    AMPERAGE_DC = auto()  # Electric current flowing in one direction only
    ANGLE = auto()  # Angular position
    ANGULAR_ACCELERATION = auto()  # Positive rate of change of angular velocity
    ANGULAR_DECELERATION = auto()  # Negative rate of change of angular velocity
    ANGULAR_VELOCITY = auto()  # Rate of change of angular position
    ASSET_UPDATE_RATE = auto()  # Average rate of change of values for assets in MTConnect streams
    AXIS_FEEDRATE = auto()  # Feedrate of a linear axis
    BATTERY_CAPACITY = auto()  # Maximum rated charge a battery can maintain
    BATTERY_CHARGE = auto()  # Value of battery's present capacity as percentage of maximum
    CAPACITY_FLUID = auto()  # Maximum amount of fluid that can be held by a container
    CAPACITY_SPATIAL = auto()  # Maximum amount of material that can be held by a container
    CHARGE_RATE = auto()  # Value of current supplied to Component for charging
    CONCENTRATION = auto()  # Percentage of one component within a mixture
    CONDUCTIVITY = auto()  # Ability of a material to conduct electricity
    CUTTING_SPEED = auto()  # Speed difference between cutting mechanism and workpiece surface
    DECELERATION = auto()  # Negative rate of change of velocity
    DENSITY = auto()  # Volumetric mass of a material per unit volume
    DEPOSITION_ACCELERATION_VOLUMETRIC = auto()  # Rate of change in spatial volume of deposited material in additive manufacturing
    DEPOSITION_DENSITY = auto()  # Density of material deposited in additive manufacturing per unit volume
    DEPOSITION_MASS = auto()  # Mass of material deposited in additive manufacturing
    DEPOSITION_RATE_VOLUMETRIC = auto()  # Rate at which spatial volume of material is deposited
    DEPOSITION_VOLUME = auto()  # Spatial volume of material to be deposited in additive manufacturing
    DEW_POINT = auto()  # Temperature at which moisture begins to condense
    DIAMETER = auto()  # Dimension of a diameter
    DISCHARGE_RATE = auto()  # Value of current being drawn from the Component
    DISPLACEMENT = auto()  # Change in position of an object
    DISPLACEMENT_ANGULAR = auto()  # Absolute value of change in angular position around a vector
    DISPLACEMENT_LINEAR = auto()  # Absolute value of change in position along a vector
    ELECTRICAL_ENERGY = auto()  # Wattage used or generated by a component over an interval of time
    EQUIPMENT_TIMER = auto()  # Amount of time equipment has performed specific activities
    FILL_LEVEL = auto()  # Amount of substance remaining compared to planned maximum
    FILL_HEIGHT = auto()  # Amount of a substance in a container
    FLOW = auto()  # Rate of flow of a fluid
    FOLLOWING_ERROR_ANGULAR = auto()  # Angular difference between commanded and actual encoder position during motion
    FOLLOWING_ERROR_LINEAR = auto()  # Difference between commanded and actual encoder position during motion
    FREQUENCY = auto()  # Number of occurrences of a repeating event per unit time
    GRAVITATIONAL_ACCELERATION = auto()  # Acceleration relative to Earth's gravity
    GRAVITATIONAL_FORCE = auto()  # Force relative to earth's gravity
    HUMIDITY_ABSOLUTE = auto()  # Amount of water vapor expressed in grams per cubic meter
    HUMIDITY_RELATIVE = auto()  # Amount of water vapor as percent to reach saturation
    HUMIDITY_SPECIFIC = auto()  # Ratio of water vapor over total weight of vapor and air
    LENGTH = auto()  # Length of an object
    LINEAR_FORCE = auto()  # Force applied to a mass in one direction only
    LOAD = auto()  # Actual versus the standard rating of equipment
    MASS = auto()  # Mass of an object(s) or an amount of material
    OBSERVATION_UPDATE_RATE = auto()  # Average rate of change of values for data items in MTConnect streams
    OPENNESS = auto()  # Percentage open where 100% is fully open and 0% is fully closed
    ORIENTATION = auto()  # Angular position of a plane or vector relative to cartesian coordinate system
    PARTICLE_COUNT = auto()  # Number of particles counted
    PARTICLE_SIZE = auto()  # Size of particles counted
    PATH_FEEDRATE = auto()  # Feedrate for the axes associated with a Path component
    PATH_FEEDRATE_PER_REVOLUTION = auto()  # Feedrate for axes per revolution
    PATH_POSITION = auto()  # Position of a control point associated with a Controller or Path
    PH = auto()  # Acidity or alkalinity of a solution
    POSITION = auto()  # Point along an axis in a cartesian coordinate system
    POSITION_CARTESIAN = auto()  # Point in a cartesian coordinate system
    POWER_FACTOR = auto()  # Ratio of real power flowing to load to apparent power in AC circuit
    PRESSURE = auto()  # Force per unit area measured relative to atmospheric pressure (gauge pressure)
    PRESSURE_ABSOLUTE = auto()  # Force per unit area measured relative to a vacuum
    PRESSURIZATION_RATE = auto()  # Change of pressure per unit time
    PROCESS_TIMER = auto()  # Amount of time equipment has performed process-related activities
    RESISTANCE = auto()  # Degree to which a substance opposes passage of electric current
    RESISTIVITY = auto()  # Inability of a material to conduct electricity
    ROTARY_VELOCITY = auto()  # Rotational speed of a rotary axis
    SETTLING_ERROR_ANGULAR = auto()  # Angular difference between commanded and actual encoder position when motion complete
    SETTLING_ERROR_LINEAR = auto()  # Difference between commanded and actual encoder position when motion complete
    SOUND_LEVEL = auto()  # Sound level or sound pressure level relative to atmospheric pressure
    STRAIN = auto()  # Amount of deformation per unit length when load applied
    TEMPERATURE = auto()  # Degree of hotness or coldness measured on a definite scale
    TENSION = auto()  # Force that stretches or elongates an object
    TILT = auto()  # Angular displacement
    TORQUE = auto()  # Turning force exerted on or by an object
    VELOCITY = auto()  # Rate of change of position of a Component
    VISCOSITY = auto()  # Fluid's resistance to flow
    VOLT_AMPERE = auto()  # Apparent power in electrical circuit (VA)
    VOLT_AMPERE_REACTIVE = auto()  # Reactive power in AC electrical circuit (VAR)
    VOLTAGE_AC = auto()  # Electrical potential in circuit with periodically reversing current
    VOLTAGE_DC = auto()  # Electrical potential in circuit with unidirectional current
    VOLUME_FLUID = auto()  # Fluid volume of an object or container
    VOLUME_SPATIAL = auto()  # Geometric volume of an object or container
    WATTAGE = auto()  # Power flowing through or dissipated by electrical circuit
    X_DIMENSION = auto()  # Dimension relative to X direction of referenced coordinate system
    Y_DIMENSION = auto()  # Dimension relative to Y direction of referenced coordinate system
    Z_DIMENSION = auto()  # Dimension relative to Z direction of referenced coordinate system


__all__ = ['SampleType']
