"""
MTConnect Models

Structural elements representing MTConnect components, data items, assets,
compositions, and references.

Relationships (ConfigurationRelationship) exist only in configurations.

Reference: MTConnect Standard v2.6 - Device Information Model
"""

# Component models
# Asset models
from mtconnect.models.assets import (
    Asset,
    AssetType,
    CutterStatus,
    CuttingTool,
    CuttingToolLifeCycle,
    File,
    FileState,
    Location,
    MaterialType,
    Measurement,
    Part,
    PartStatus,
    QIFDocumentWrapper,
    RawMaterial,
    ToolLife,
    ToolLifeDirection,
    ToolLifeType,
)
from mtconnect.models.components import (
    Actuator,
    Adapter,
    Adapters,
    Agent,
    AirHandler,
    Amplifier,
    AutomaticToolChanger,
    Auxiliaries,
    Auxiliary,
    Axes,
    Axis,
    Ballscrew,
    BarFeeder,
    BarFeederInterface,
    Belt,
    Brake,
    Chain,
    Chopper,
    Chuck,
    ChuckInterface,
    Chute,
    CircuitBreaker,
    Clamp,
    Component,
    Compressor,
    Controller,
    Controllers,
    Coolant,
    Cooling,
    CoolingTower,
    CuttingTorch,
    Deposition,
    Description,
    Device,
    Dielectric,
    Door,
    DoorInterface,
    Drain,
    Electric,
    Electrode,
    Enclosure,
    Encoder,
    EndEffector,
    Environmental,
    ExpiredPot,
    ExposureUnit,
    ExtrusionUnit,
    Fan,
    FeatureOccurrence,
    Feeder,
    Filter,
    Galvanomotor,
    GangToolBar,
    Gripper,
    Heating,
    Hopper,
    Hydraulic,
    Interface,
    Interfaces,
    Linear,
    LinearPositionFeedback,
    Link,
    Loader,
    Lock,
    Lubrication,
    Material,
    MaterialHandlerInterface,
    Materials,
    Motor,
    Oil,
    PartOccurrence,
    Parts,
    Path,
    Personnel,
    Pneumatic,
    Pot,
    PowerSupply,
    Pressure,
    Processes,
    ProcessOccurrence,
    ProcessPower,
    Protective,
    Pulley,
    Pump,
    Reel,
    RemovalPot,
    Requester,
    Resource,
    Resources,
    Responder,
    ReturnPot,
    Rotary,
    SensingElement,
    Sensor,
    Spindle,
    Spreader,
    StagingPot,
    Station,
    Stock,
    StorageBattery,
    Structure,
    Structures,
    Switch,
    System,
    Systems,
    Table,
    Tank,
    Tensioner,
    ToolingDelivery,
    ToolMagazine,
    ToolRack,
    TransferArm,
    TransferPot,
    Transformer,
    Turret,
    Vacuum,
    Valve,
    Vat,
    WasteDisposal,
    Water,
    Wire,
    WorkEnvelope,
    Workpiece,
)
from mtconnect.models.components import Composition as CompositionComponent
from mtconnect.models.components import Part as PartComponent
from mtconnect.models.components import Process as ProcessComponent

# Composition models
from mtconnect.models.compositions import (
    Composition,
)

# Configuration models
from mtconnect.models.configurations import (
    AlarmLimits,
    ControlLimits,
    SpecificationLimits,
    Configuration,
    ConfigurationRelationship,
    CoordinateSystem,
    ImageFile,
    Motion,
    PowerSource,
    SensorConfiguration,
    SolidModel,
    Specification,
)

# DataItem models
from mtconnect.models.data_items import (
    ConditionDataItem,
    Constraints,
    DataItem,
    DataItemCategory,
    EventDataItem,
    SampleDataItem,
)

# Reference models
from mtconnect.models.references import (
    Reference,
    ComponentRef,
    DataItemRef,
)

# Observation value models
from mtconnect.models.values import (
    AlarmLimitsValue,
    Condition,
    ControlLimitsValue,
    DataSet,
    Event,
    Observation,
    Sample,
    SpecificationLimitsValue,
    TimeSeries,
    UnavailableType,
)

__all__ = [
    "Actuator",
    "Adapter",
    "Adapters",
    "Agent",
    "AirHandler",
    "AlarmLimitsValue",
    "Amplifier",
    # Assets
    "Asset",
    "AssetType",
    "AutomaticToolChanger",
    "Auxiliaries",
    "Auxiliary",
    "Axes",
    "Axis",
    "Ballscrew",
    "BarFeeder",
    "BarFeederInterface",
    "Belt",
    "Brake",
    "Chain",
    "Chopper",
    "Chuck",
    "ChuckInterface",
    "Chute",
    "CircuitBreaker",
    "Clamp",
    # Components
    "Component",
    # References
    "ComponentRef",
    # Compositions
    "Composition",
    "Compressor",
    "Condition",
    "ConditionDataItem",
    "AlarmLimits",
    "ControlLimits",
    "SpecificationLimits",
    # Configuration
    "Configuration",
    "ConfigurationRelationship",
    "Constraints",
    "ControlLimitsValue",
    "Controller",
    "Controllers",
    "Coolant",
    "Cooling",
    "CoolingTower",
    "CoordinateSystem",
    "CutterStatus",
    "CuttingTool",
    "CuttingToolLifeCycle",
    "CuttingTorch",
    # DataItems
    "DataItem",
    "DataItemCategory",
    "DataItemRef",
    "DataSet",
    "Deposition",
    "Description",
    "Device",
    "Dielectric",
    "Door",
    "DoorInterface",
    "Drain",
    "Electric",
    "Electrode",
    "Enclosure",
    "Encoder",
    "EndEffector",
    "Environmental",
    "Event",
    "EventDataItem",
    "ExpiredPot",
    "ExposureUnit",
    "ExtrusionUnit",
    "Fan",
    "FeatureOccurrence",
    "Feeder",
    "File",
    "FileState",
    "Filter",
    "Galvanomotor",
    "GangToolBar",
    "Gripper",
    "Heating",
    "Hopper",
    "Hydraulic",
    "ImageFile",
    "Interface",
    "Interfaces",
    "Linear",
    "LinearPositionFeedback",
    "Link",
    "Loader",
    "Location",
    "Lock",
    "Lubrication",
    "Material",
    "MaterialHandlerInterface",
    "MaterialType",
    "Materials",
    "Measurement",
    "Motion",
    "Motor",
    # Values
    "Observation",
    "Oil",
    "Part",
    "PartComponent",
    "PartOccurrence",
    "PartStatus",
    "Parts",
    "Path",
    "Personnel",
    "Pneumatic",
    "Pot",
    "PowerSource",
    "PowerSupply",
    "Pressure",
    "ProcessComponent",
    "ProcessOccurrence",
    "ProcessPower",
    "Processes",
    "Protective",
    "Pulley",
    "Pump",
    "QIFDocumentWrapper",
    "RawMaterial",
    "Reel",
    "Reference",
    "RemovalPot",
    "Requester",
    "Resource",
    "Resources",
    "Responder",
    "ReturnPot",
    "Rotary",
    "SampleDataItem",
    "Sample",
    "SensingElement",
    "Sensor",
    "SensorConfiguration",
    "SolidModel",
    "Specification",
    "SpecificationLimitsValue",
    "Spindle",
    "Spreader",
    "StagingPot",
    "Station",
    "Stock",
    "StorageBattery",
    "Structure",
    "Structures",
    "Switch",
    "System",
    "Systems",
    "Table",
    "Tank",
    "Tensioner",
    "TimeSeries",
    "ToolLife",
    "ToolLifeDirection",
    "ToolLifeType",
    "ToolMagazine",
    "ToolRack",
    "ToolingDelivery",
    "TransferArm",
    "TransferPot",
    "Transformer",
    "Turret",
    "UnavailableType",
    "Vacuum",
    "Valve",
    "Vat",
    "WasteDisposal",
    "Water",
    "Wire",
    "WorkEnvelope",
    "Workpiece",
]
