"""
MTConnect Enumeration Types

Additional enumeration types extracted from the MTConnect normative model
version 2.6. These enums represent standardized values for units, states,
representations, and other categorical values used in MTConnect.

Reference: MTConnect Standard v2.6 Normative Model
Auto-generated from: model_2.6.xml
"""

from enum import Enum, auto



################################################################################
# Observation Value Enumerations
################################################################################

class SampleType(Enum):
    """SampleType values from MTConnect SampleEnum"""

    ACCELERATION = auto()  # positive rate of change of velocity.
    ACCUMULATED_TIME = auto()  # accumulated time for an activity or event.
    AMPERAGE = auto()  # strength of electrical current. **DEPRECATED** in *Version 1.6*. Replaced by ...
    ANGLE = auto()  # angular position.
    ANGULAR_ACCELERATION = auto()  # positive rate of change of angular velocity.
    ANGULAR_VELOCITY = auto()  # rate of change of angular position.
    AXIS_FEEDRATE = auto()  # feedrate of a linear axis.
    CAPACITY_FLUID = auto()  # maximum amount of fluid that can be held by a container.
    CAPACITY_SPATIAL = auto()  # maximum amount of material that can be held by a container.
    CONCENTRATION = auto()  # percentage of one component within a mixture of components.
    CONDUCTIVITY = auto()  # ability of a material to conduct electricity.
    CUTTING_SPEED = auto()  # speed difference (relative velocity) between the cutting mechanism and the su...
    DENSITY = auto()  # volumetric mass of a material per unit volume of that material.
    DEPOSITION_ACCELERATION_VOLUMETRIC = auto()  # rate of change in spatial volume of material deposited in an additive manufac...
    DEPOSITION_DENSITY = auto()  # density of the material deposited in an additive manufacturing process per un...
    DEPOSITION_MASS = auto()  # mass of the material deposited in an additive manufacturing process.
    DEPOSITION_RATE_VOLUMETRIC = auto()  # rate at which a spatial volume of material is deposited in an additive manufa...
    DEPOSITION_VOLUME = auto()  # spatial volume of material to be deposited in an additive manufacturing process.
    DISPLACEMENT = auto()  # change in position of an object.
    ELECTRICAL_ENERGY = auto()  # Wattage used or generated by a component over an interval of time.
    EQUIPMENT_TIMER = auto()  # amount of time a piece of equipment or a sub-part of a piece of equipment has...
    FILL_LEVEL = auto()  # amount of a substance remaining compared to the planned maximum amount of tha...
    FLOW = auto()  # rate of flow of a fluid.
    FREQUENCY = auto()  # number of occurrences of a repeating event per unit time.
    GLOBAL_POSITION = auto()  # position in three-dimensional space. **DEPRECATED** in Version 1.1.
    LENGTH = auto()  # length of an object.
    LEVEL = auto()  # level of a resource. **DEPRECATED** in *Version 1.2*. See `FILL_LEVEL`.
    LINEAR_FORCE = auto()  # force applied to a mass in one direction only.
    LOAD = auto()  # actual versus the standard rating of a piece of equipment.
    MASS = auto()  # mass of an object(s) or an amount of material.
    PATH_FEEDRATE = auto()  # feedrate for the axes, or a single axis, associated with a Path component.
    PATH_FEEDRATE_PER_REVOLUTION = auto()  # feedrate for the axes, or a single axis.
    PATH_POSITION = auto()  # position of a control point associated with a Controller or a Path.
    PH = auto()  # acidity or alkalinity of a solution.
    POSITION = auto()  # point along an axis in a cartesian coordinate system.
    POWER_FACTOR = auto()  # ratio of real power flowing to a load to the apparent power in that AC circuit.
    PRESSURE = auto()  # force per unit area measured relative to atmospheric pressure. Commonly refer...
    PROCESS_TIMER = auto()  # amount of time a piece of equipment has performed different types of activiti...
    RESISTANCE = auto()  # degree to which a substance opposes the passage of an electric current.
    ROTARY_VELOCITY = auto()  # rotational speed of a rotary axis.
    SOUND_LEVEL = auto()  # sound level or sound pressure level relative to atmospheric pressure.
    SPINDLE_SPEED = auto()  # rotational speed of the rotary axis. **DEPRECATED** in *Version 1.2*. Replace...
    STRAIN = auto()  # amount of deformation per unit length of an object when a load is applied.
    TEMPERATURE = auto()  # degree of hotness or coldness measured on a definite scale.
    TENSION = auto()  # force that stretches or elongates an object.
    TILT = auto()  # angular displacement.
    TORQUE = auto()  # turning force exerted on an object or by an object.
    VELOCITY = auto()  # rate of change of position of a Component.
    VISCOSITY = auto()  # fluid's resistance to flow.
    VOLTAGE = auto()  # electrical potential between two points. **DEPRECATED** in *Version 1.6*. Rep...
    VOLT_AMPERE = auto()  # apparent power in an electrical circuit, equal to the product of root-mean-sq...
    VOLT_AMPERE_REACTIVE = auto()  # reactive power in an AC electrical circuit (commonly referred to as VAR).
    VOLUME_FLUID = auto()  # fluid volume of an object or container.
    VOLUME_SPATIAL = auto()  # geometric volume of an object or container.
    WATTAGE = auto()  # power flowing through or dissipated by an electrical circuit or piece of equi...
    AMPERAGE_AC = auto()  # electrical current that reverses direction at regular short intervals.
    AMPERAGE_DC = auto()  # electric current flowing in one direction only.
    VOLTAGE_AC = auto()  # electrical potential between two points in an electrical circuit in which the...
    VOLTAGE_DC = auto()  # electrical potential between two points in an electrical circuit in which the...
    X_DIMENSION = auto()  # dimension of an entity relative to the X direction of the referenced coordina...
    Y_DIMENSION = auto()  # dimension of an entity relative to the Y direction of the referenced coordina...
    Z_DIMENSION = auto()  # dimension of an entity relative to the Z direction of the referenced coordina...
    DIAMETER = auto()  # dimension of a diameter.
    ORIENTATION = auto()  # angular position of a plane or vector relative to a cartesian coordinate system
    HUMIDITY_RELATIVE = auto()  # amount of water vapor present expressed as a percent to reach saturation at t...
    HUMIDITY_ABSOLUTE = auto()  # amount of water vapor expressed in grams per cubic meter.
    HUMIDITY_SPECIFIC = auto()  # ratio of the water vapor present over the total weight of the water vapor and...
    OBSERVATION_UPDATE_RATE = auto()  # average rate of change of values for data items in the MTConnect streams. The...
    ASSET_UPDATE_RATE = auto()  # average rate of change of values for assets in the MTConnect streams. The ave...
    PRESSURIZATION_RATE = auto()  # change of pressure per unit time.
    DECELERATION = auto()  # negative rate of change of velocity.
    ANGULAR_DECELERATION = auto()  # negative rate of change of angular velocity.
    PRESSURE_ABSOLUTE = auto()  # force per unit area measured relative to a vacuum.
    OPENNESS = auto()  # percentage open where 100% is fully open and 0% is fully closed.
    DEW_POINT = auto()  # temperature at which moisture begins to condense, corresponding to saturation...
    GRAVITATIONAL_FORCE = auto()  # force relative to earth's gravity.
    GRAVITATIONAL_ACCELERATION = auto()  # acceleration relative to Earth's gravity of 9.80665 `METER/SECOND^2`.
    BATTERY_CAPACITY = auto()  # maximum rated charge a battery is capable of maintaining based on the battery...
    DISCHARGE_RATE = auto()  # value of current being drawn from the Component.
    CHARGE_RATE = auto()  # value of the current being supplied to the Component for the purpose of charg...
    BATTERY_CHARGE = auto()  # value of the battery's present capacity expressed as a percentage of the batt...
    SETTLING_ERROR = auto()  # difference between actual and commanded position at the end of a motion.
    FOLLOWING_ERROR = auto()  # difference between actual and commanded position at any specific point in tim...
    SETTLING_ERROR_LINEAR = auto()  # difference between the commanded encoder/resolver position, and the actual en...
    SETTLING_ERROR_ANGULAR = auto()  # angular difference between the commanded encoder/resolver position, and the a...
    FOLLOWING_ERROR_LINEAR = auto()  # difference between the commanded encoder/resolver position and the actual enc...
    FOLLOWING_ERROR_ANGULAR = auto()  # angular difference between the commanded encoder/resolver position and the ac...
    DISPLACEMENT_LINEAR = auto()  # absolute value of the change in position along a vector.
    DISPLACEMENT_ANGULAR = auto()  # absolute value of the change in angular position around a vector
    POSITION_CARTESIAN = auto()  # point in a cartesian coordinate system.
    RESISTIVITY = auto()  # inability of a material to conduct electricity.
    FILL_HEIGHT = auto()  # amount of a substance in a container.
    PARTICLE_COUNT = auto()  # number of particles counted by their size or other characteristics.
    PARTICLE_SIZE = auto()  # size of particles counted by their size or other characteristics.

